name: reusable-release
on:
  workflow_call:
    inputs:
      version_file:
        description: Version file path
        required: false
        default: framework-version
        type: string
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          test -f "${{ inputs.version_file }}" && cat "${{ inputs.version_file }}" || echo "missing version file"
